/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SmartRouteImport } from './routes/smart'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MembersRouteImport } from './routes/members'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ChoresRouteImport } from './routes/chores'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartRoute = SmartRouteImport.update({
  id: '/smart',
  path: '/smart',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresRoute = ChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/kitchen': typeof KitchenRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/smart': typeof SmartRoute
  '/stats': typeof StatsRoute
  '/weather': typeof WeatherRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/kitchen': typeof KitchenRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/smart': typeof SmartRoute
  '/stats': typeof StatsRoute
  '/weather': typeof WeatherRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/kitchen': typeof KitchenRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/smart': typeof SmartRoute
  '/stats': typeof StatsRoute
  '/weather': typeof WeatherRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chores'
    | '/kitchen'
    | '/members'
    | '/settings'
    | '/smart'
    | '/stats'
    | '/weather'
    | '/api/auth/google'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chores'
    | '/kitchen'
    | '/members'
    | '/settings'
    | '/smart'
    | '/stats'
    | '/weather'
    | '/api/auth/google'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/chores'
    | '/kitchen'
    | '/members'
    | '/settings'
    | '/smart'
    | '/stats'
    | '/weather'
    | '/api/auth/google'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChoresRoute: typeof ChoresRoute
  KitchenRoute: typeof KitchenRoute
  MembersRoute: typeof MembersRoute
  SettingsRoute: typeof SettingsRoute
  SmartRoute: typeof SmartRoute
  StatsRoute: typeof StatsRoute
  WeatherRoute: typeof WeatherRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart': {
      id: '/smart'
      path: '/smart'
      fullPath: '/smart'
      preLoaderRoute: typeof SmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChoresRoute: ChoresRoute,
  KitchenRoute: KitchenRoute,
  MembersRoute: MembersRoute,
  SettingsRoute: SettingsRoute,
  SmartRoute: SmartRoute,
  StatsRoute: StatsRoute,
  WeatherRoute: WeatherRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
